SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `tododbase` DEFAULT CHARACTER SET utf8 ;
USE `tododbase` ;

DROP TABLE IF EXISTS `todobase` ;


CREATE TABLE IF NOT EXISTS `todobase` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Date` VARCHAR(30) NOT NULL,
  `WhatTODO` VARCHAR(100) NOT NULL,
  `Status` BOOLEAN NOT NULL,

  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1002;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
#  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
# DATETIME